name: Secret creator

on:
  workflow_dispatch:
    inputs:
      secretName:
        description: 'Define name of secret'
        required: true
      secretValue:
        description: 'Define secret in json format'     
        required: true
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Instlal git-crypt
      run: sudo apt-get install -y git-crypt

    - name: Unlock secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

    - name: echo
      run: |
        echo "Secret value: ${{ github.event.inputs.secretValue }}"
        echo "Secret name : ${{ github.event.inputs.secretName }}"
    - name: Save to file
      run: |
        mkdir -p secrets
        echo '${{ github.event.inputs.secretValue }}' | jq '.' > secrets/${{ github.event.inputs.secretName }}.json
        ls -l secrets
        cat secrets/${{ github.event.inputs.secretName }}.json

    - name: Create PR to applications-infra
      uses: peter-evans/create-pull-request@v3
      with:
        branch: feature/add-${{ github.event.inputs.secretName }}-secret
        title: Add ${{ github.event.inputs.secretName }}" secret
        commit-message: Add ${{ github.event.inputs.secretName }}" secret
        body: secret manager