name: Secret creator

on:
  workflow_dispatch:
    inputs:
      secretName:
        description: 'Define name of secret'
        required: true
      secretValue:
        description: 'Define secret in json format'     
        required: true
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: |
        echo "Secret value: ${{ github.event.inputs.secretValue }}"
        echo "Secret name : ${{ github.event.inputs.secretName }}"
    - name: Save to file
      run: |
        mkdir -p secrets
        echo ${{ github.event.inputs.secretName }} > secrets/${{ github.event.inputs.secretName }}.json
        ls -l
        cat secrets/${{ github.event.inputs.secretName }}.json