name: Secret creator

on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Define secret in json format'     
        required: true
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Env: ${{ github.event.inputs.secret }}" 
